// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1706954266);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1707018089);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1706957866);
user_pref("app.update.lastUpdateTime.region-update-timer", 1706782224);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1707018092);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1706954266);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1706782255);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1706954266);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{fac98396-1f50-40ce-abec-c1993981f9b3}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1706782193);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 142);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2db89c8b-4140-411c-bb6f-01931aed802a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240108143603");
user_pref("browser.startup.homepage_override.mstone", "121.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1707018060);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1706782259251");
user_pref("devtools.debugger.prefs-schema-version", 11);
user_pref("devtools.everOpened", true);
user_pref("devtools.netmonitor.columnsData", "[{\"name\":\"status\",\"minWidth\":30,\"width\":6.67},{\"name\":\"method\",\"minWidth\":30,\"width\":6.67},{\"name\":\"domain\",\"minWidth\":30,\"width\":13.33},{\"name\":\"file\",\"minWidth\":30,\"width\":33.34},{\"name\":\"url\",\"minWidth\":30,\"width\":25},{\"name\":\"initiator\",\"minWidth\":30,\"width\":13.33},{\"name\":\"type\",\"minWidth\":30,\"width\":6.67},{\"name\":\"transferred\",\"minWidth\":30,\"width\":13.33},{\"name\":\"contentSize\",\"minWidth\":30,\"width\":6.67},{\"name\":\"waterfall\",\"minWidth\":150,\"width\":10}]");
user_pref("devtools.netmonitor.msg.visibleColumns", "[\"data\",\"time\"]");
user_pref("devtools.performance.recording.entries", 134217728);
user_pref("devtools.performance.recording.features", "[\"screenshots\",\"js\",\"cpu\"]");
user_pref("devtools.performance.recording.threads", "[\"GeckoMain\",\"Compositor\",\"Renderer\",\"DOM Worker\"]");
user_pref("devtools.toolbox.selectedTool", "webconsole");
user_pref("devtools.toolbox.splitconsoleEnabled", true);
user_pref("devtools.webconsole.filter.css", true);
user_pref("devtools.webconsole.filter.net", true);
user_pref("devtools.webconsole.filter.netxhr", true);
user_pref("devtools.webconsole.persistlog", true);
user_pref("devtools.webconsole.timestampMessages", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "121.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1706954300);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240108143603");
user_pref("extensions.lastAppVersion", "121.0.1");
user_pref("extensions.lastPlatformVersion", "121.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"631a387c-d644-401b-b033-b682df899800\",\"pictureinpicture@mozilla.org\":\"faad9916-c3bf-45a3-bd16-38160c717971\",\"screenshots@mozilla.org\":\"bc447cc1-8d72-4164-b086-24930f816723\",\"webcompat-reporter@mozilla.org\":\"896ffb22-a1cc-4766-8a02-b89da9387e62\",\"webcompat@mozilla.org\":\"3ed90ac9-aa20-4f1b-bd4d-96be4bbfd7bf\",\"default-theme@mozilla.org\":\"7630981a-6bb6-4a02-8c2b-866c8db6d312\",\"addons-search-detection@mozilla.com\":\"45fdf293-0751-4ed1-a4f8-f236c03515c1\",\"google@search.mozilla.org\":\"27385184-492c-4531-b5f9-ecc584342d6c\",\"amazondotcom@search.mozilla.org\":\"003349f5-808b-4574-ba59-956cd112e95f\",\"wikipedia@search.mozilla.org\":\"49a5a973-04c5-40cb-9a7e-f0a6475012f2\",\"bing@search.mozilla.org\":\"dff852ff-62a9-4f36-85ff-79595f1805d1\",\"ddg@search.mozilla.org\":\"38ee7f5f-659f-4d00-8ec8-fb4aabad745d\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1706954664);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2152398878, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1706954554);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1706954522);
user_pref("media.gmp-manager.buildID", "20240108143603");
user_pref("media.gmp-manager.lastCheck", 1706954522);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1706782668);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1706954664960");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "b412be41-ccb5-43a6-959e-08b60e51dfe5");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("storage.vacuum.last.content-prefs.sqlite", 1706954664);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1706782668);
user_pref("toolkit.startup.last_success", 1707018058);
user_pref("toolkit.telemetry.cachedClientID", "6cc01df9-b9d6-4902-a08a-e2354df664e2");
user_pref("toolkit.telemetry.previousBuildID", "20240108143603");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
